#!/bin/sh
# Emit the homebrew formula for one release to stdout.
#
#   brew-formula.sh v0.7.0 dist/checksums.txt > Formula/truthboard.rb
#
# The release workflow runs this on every tag and pushes the result to the
# tap repo (emmanuel-D/homebrew-truthboard). A missing checksum for any of
# the four brew platforms is a hard error — a formula that 404s for half
# its users must never ship.
set -eu

[ $# -eq 2 ] || { echo "usage: brew-formula.sh <tag> <checksums.txt>" >&2; exit 2; }
tag="$1"
sums="$2"

sha() {
  s=$(awk -v f="truthboard_${tag}_$1.tar.gz" '$2 == f { print $1 }' "$sums")
  [ -n "$s" ] || { echo "brew-formula.sh: no checksum for $1 in $sums" >&2; exit 1; }
  printf '%s' "$s"
}

# Resolved before the heredoc: a failed substitution inside one would print
# the formula anyway and exit 0 — set -e only sees these assignments.
sha_darwin_arm64=$(sha darwin_arm64)
sha_darwin_amd64=$(sha darwin_amd64)
sha_linux_arm64=$(sha linux_arm64)
sha_linux_amd64=$(sha linux_amd64)

cat <<EOF
# Generated by truthboard's release workflow for ${tag} — do not edit.
class Truthboard < Formula
  desc "Task tracking where statuses are derived from git, never typed"
  homepage "https://github.com/emmanuel-D/truthboard"
  version "${tag#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/emmanuel-D/truthboard/releases/download/${tag}/truthboard_${tag}_darwin_arm64.tar.gz"
      sha256 "${sha_darwin_arm64}"
    end
    on_intel do
      url "https://github.com/emmanuel-D/truthboard/releases/download/${tag}/truthboard_${tag}_darwin_amd64.tar.gz"
      sha256 "${sha_darwin_amd64}"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/emmanuel-D/truthboard/releases/download/${tag}/truthboard_${tag}_linux_arm64.tar.gz"
      sha256 "${sha_linux_arm64}"
    end
    on_intel do
      url "https://github.com/emmanuel-D/truthboard/releases/download/${tag}/truthboard_${tag}_linux_amd64.tar.gz"
      sha256 "${sha_linux_amd64}"
    end
  end

  def install
    bin.install "truthboard"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/truthboard version")
  end
end
EOF
